DWAPlannerROS:
  # Velocity
  max_vel_x: 0.3
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  acc_lim_x: 1.0
  acc_lim_theta: 2.0

  # Goal Tolerance
  yaw_goal_tolerance: 0.17
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: true

  # Forward Simulation
  sim_time: 1.2
  sim_granularity: 0.025
  vx_samples: 20
  vtheta_samples: 40
  controller_frequency: 10.0

  # Obstacle Avoidance
  path_distance_bias: 24.0
  goal_distance_bias: 16.0
  occdist_scale: 10.0

  # Trajectory tuning
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.1

  # Debug tools
  publish_traj_pc: true
  publish_cost_grid_pc: true
  meter_scoring: true
  prune_plan: true