TrajectoryPlannerROS:
  max_vel_x: 10
  min_vel_x: -10
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.25

  acc_lim_theta: 0.25
  acc_lim_X: 10
  acc_lim_Y: 10
  
  holonomic_robot: false
  meter_scoring: true

  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 1
  
