version: '3'
services:
  ros2:
    build: .
    container_name: igvc_ros2
    volumes:
      - .:/root/igvc_2025
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    command: bash -c "ros2 launch autonav_bringup competition.launch.py"
